module.exports = {
  mySidebar: [
    'getting-started',
    {
      type: 'category',
      label: '파이썬',
      items: [
        {
          type: 'category',
          label: '시작하기',
          items: [
            {
              type: 'autogenerated',
              dirName: 'python/start',
            },
          ],
        }, {
          type: 'category',
          label: '데이터 타입',
          items: [
            {
              type: 'autogenerated',
              dirName: 'python/data-types',
            },
          ],
        },
      ],
    },
  ],
};
